sudo: required
services:
  - docker


before_install:
  # Load cached docker images
  - if [[ -d $HOME/docker ]]; then ls $HOME/docker/*.tar.gz | xargs -I {file} sh -c "zcat {file} | docker load"; fi
  - docker build -t ajammil/kwikker/frontendtest -f Dockerfile.dev .

before_cache:
  # Save tagged docker images
  - >
    mkdir -p $HOME/docker && docker images -a --filter='dangling=false' --format '{{.Repository}}:{{.Tag}} {{.ID}}'
    | xargs -n 2 -t sh -c 'test -e $HOME/docker/$1.tar.gz || docker save $0 | gzip -2 > $HOME/docker/$1.tar.gz'

cache:
  bundler: true
  directories:
    - $HOME/docker

script:
  - gem install bundler
#tests will be here
# run tests (not yet working)
  - docker run ajammil/kwikker/frontendtest ng test --karmaConfig=./src/karma.prod.conf.js --watch=false

after_success:
  #build production image
  - docker build -t ajammil/kwikkerfrontend:latest .
  #Log in to docker hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #Push image to docker hub
  - docker push ajammil/kwikkerfrontend:latest

deploy:
  provider: elasticbeanstalk
  region: eu-central-1
  app: Kwikker frontend
  env: KwikkerFrontend-env
  bucket_name: elasticbeanstalk-eu-central-1-911980560928
  bucket_path: frontend-kwikker
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
